version: '3.8'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app
    working_dir: /app
    command: sh -c "npm install -g react-scripts && npm start"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
