# Use the official PostgreSQL image as a base image
FROM postgres:15

# Add custom configurations if needed
# COPY custom-config-file.conf /etc/postgresql/

# Expose the PostgreSQL port (5432) if necessary
# EXPOSE 5432

# You can add environment variables or other setup here

# Define an entrypoint if necessary
# ENTRYPOINT ["entrypoint.sh"]

# CMD ["postgres"]

# Optionally, you can specify a user and group for the PostgreSQL process
# USER postgres
